version: '3'

services:
  fpm:
    restart: always
    image: php:7-fpm
    container_name: nginx_php
    build:
      context: ./
      dockerfile: ./php.dockerfile
    volumes:
      - ./include:/include
      - ./public:/public
    working_dir: /public
    ports:
      - "9000"
    # network_mode: "host"

  redis:
    image: redis:4.0.5-alpine
    container_name: nginx_redis
    # command: ["redis-server", "--appendonly", "yes"]
    command: ["redis-server"]
    ports:
      - "6379:6379"
    # network_mode: "host"
    volumes:
      - ./data:/data

  nginx:
    restart: always
    image: nginx:1.0.0
    container_name: nginx_v100
    build:
      context: ./
      dockerfile: ./nginx.dockerfile
    working_dir: /public
    # command: make run
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
      - ./logs:/logs
      - ./include:/include
      - ./public:/public
    # command: [nginx-debug, '-g', 'daemon off;']
    # network_mode: "host"
    depends_on:
        - fpm

networks:
  default:
    external:
      name: local-nginx
