version: '3'

services:
  redis:
    restart: always
    image: redis:4.0.5-alpine
    container_name: nginx_redis
    command: ["redis-server"]
    volumes:
      - ./data:/data

  fpm:
    restart: always
    image: php:7-fpm
    container_name: nginx_php
    build:
      context: ./
      dockerfile: ./php.dockerfile
    volumes:
      - ./include:/include
      - ./public:/public
    working_dir: /public

  nginx:
    restart: always
    image: nginx:1.0.0
    container_name: nginx
    build:
      context: ./
      dockerfile: ./nginx.dockerfile
    working_dir: /public
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
      - ./logs:/logs
      - ./include:/include
      - ./public:/public

networks:
  default:
    external:
      name: nginx-network
